CREATE TABLE Buyers(
                       Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                       BuyerId BIGINT NOT NULL,
                       EntityTitle VARCHAR(100) NOT NULL DEFAULT('Empty'),
                       RegistrationNumber VARCHAR(30) NOT NULL DEFAULT('Empty'),
                       LegalAddress VARCHAR(100) NOT NULL DEFAULT('Empty'),
                       RealAddress VARCHAR(100) NOT NULL DEFAULT('Empty'),
                       PhoneNumber VARCHAR(20) NOT NULL DEFAULT('Empty'),
                       EmailAddress VARCHAR(30) NOT NULL DEFAULT('Empty'),
                       Balance DECIMAL(10, 2) NOT NULL DEFAULT('0'),
                       Status VARCHAR(10) NOT NULL DEFAULT('None'),
                       Login VARCHAR(30) NOT NULL,
                       Password VARCHAR(30) NOT NULL,
                       Role VARCHAR(10) NOT NULL DEFAULT('Buyer'),
                       CONSTRAINT `Buyers_chk1` CHECK (BuyerId NOT LIKE ''),
                       CONSTRAINT `Buyers_chk2` CHECK (EntityTitle NOT LIKE ''),
                       CONSTRAINT `Buyers_chk3` CHECK (RegistrationNumber NOT LIKE ''),
                       CONSTRAINT `Buyers_chk4` CHECK (LegalAddress NOT LIKE ''),
                       CONSTRAINT `Buyers_chk5` CHECK (RealAddress NOT LIKE ''),
                       CONSTRAINT `Buyers_chk6` CHECK (PhoneNumber NOT LIKE ''),
                       CONSTRAINT `Buyers_chk7` CHECK (EmailAddress NOT LIKE ''),
                       CONSTRAINT `Buyers_chk8` CHECK (Status IN ('None', 'Active', 'Inactive', 'Blocked')),
                       CONSTRAINT `Buyers_chk9` CHECK (Login NOT LIKE ''),
                       CONSTRAINT `Buyers_chk10` CHECK (Password NOT LIKE ''),
                       CONSTRAINT `Buyers_chk11` CHECK (ROLE IN ('Buyer', 'Admin'))
);